on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-docker:
    name: 'Build Docker Container'
    runs-on: ubuntu-latest
    services:
       registry:
         image: registry:2
         ports:
           - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: true
          tags: localhost:5000/qiime2/testq2dataflow:latest
